services:
  mongodb-statistics:
    build:
      context: .
      dockerfile: Dockerfile
      # Use the production target by default
      target: production
      args:
        - NODE_ENV=production
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    # Uncomment these lines for development mode:
    # volumes:
    #   - .:/app
    #   - /app/node_modules
    #   - /app/.next
    # command: npm run dev 